"""Add address column to Department model

Revision ID: d1e1a1144306
Revises: 52cca81fbd56
Create Date: 2024-06-26 18:56:31.853943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e1a1144306'
down_revision = '52cca81fbd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('department', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('salary', sa.INTEGER(), nullable=True))
    op.drop_column('department', 'address')
    # ### end Alembic commands ###
